name: collector
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  image_field:
    git:
      url: https://github.com/Protoss78/flutter_image_field.git
      ref: main
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Gorditas
      fonts:
        - asset: assets/fonts/Gorditas-Regular.ttf
        - asset: assets/fonts/Gorditas-Bold.ttf
          weight: 700